[COMMON]
SERVER_IP=192.168.0.50
SERVER_MD_PORT=9129
SERVER_RESEND_PORT=9130

[LOGON]
SENDER_NAME=MYSENDER
RECEIVER_NAME=MYRECEIVER
HEART_BEAT_INT=30
PASSWORD=MYPASSWD
VERSION=1.0.1

[LOG]
LOG_FILE=log/md.log
#trace debug info warning error
LOG_LEVEL=trace

[PERF]
POP_TIMEOUT=1
